config/routes.rb
Gallery::Application.routes.draw do
  
  controller :sessions do 
    get  'login'  => :new
    post 'login'  => :create
    get  'logout' => :destroy
  end

  controller :contact do 
    get 'contact' => :new
    post 'contact' => :create
  end

  resources :admins, controller: 'admin', path: 'admin'
  resources :galleries

  root to: 'galleries#index'
end

app/models/image.rb
require 'carrierwave/orm/activerecord'

class Image < ActiveRecord::Base
	belongs_to :image_store

	#rends accesible les champs passer dans ma BD, par defaut tout es inaccesible !
	attr_accessible :title, :description, :image, :image_store_id
	
	validates_presence_of :image

	mount_uploader :image, ImagesUploader
end

app/models/image_store.rb
class ImageStore < ActiveRecord::Base

	has_many :images

	validates_presence_of :name

	#rends accesible les champs passer dans ma BD, par defaut tout es inaccesible !
	attr_accessible :name, :description
end

app/models/message.rb
# encoding: utf-8

class Message
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  
  attr_accessor :name, :email, :content
  
  validates_presence_of :name, :message => "Le champ prénom doit être rempli"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i, :message => "Le champ email n'est pas au bon format"
  validates_presence_of :content, :message => "Le champ message doit être rempli"
  validates_length_of :content, :maximum => 500, :message => "Le champ message doit être rempli"

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  
  def persisted?
    false
  end
end

app/controllers/admin_controller.rb
require 'zippy'

class AdminController < ApplicationController
	before_filter :authentication_required

	def index
    @image_stores = ImageStore.all
    @images = Image.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end


  def new
    @image_store = ImageStore.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET 
  def edit
    @image_store = ImageStore.find(params[:id])
  end

  # POST 
  def create
    @image_store = ImageStore.new(:name => params[:image_store][:name], :description => params[:image_store][:description])
    
    Zippy.each(params[:image_store][:image].path) do |filename, data|
      if data.present? && File.basename(filename) !~ /^\./
        file = CarrierWave::SanitizedFile.new({
          :tempfile => StringIO.new(data),
          :filename => filename,
          :content_type => content_type_of_filename(filename)
        })
        image = @image_store.images.build(:title => File.basename(filename))
        image.image = file
      end
    end

    respond_to do |format|
      if @image_store.save!
          format.html { redirect_to admins_url }
      else
        format.html { render action: "new" }
      end
    end
  end
 
  # PUT 
  def update
    @image_store = ImageStore.find(params[:id])

    respond_to do |format|
      if @image_store.update_attributes(:name => params[:image_store][:name], :description => params[:image_store][:description])
        format.html { redirect_to admins_url }
      else
        format.html { render action: "edit" }
      end 
    end
  end
  
  # DELETE 
  def destroy
    @image_store = ImageStore.find(params[:id])
    @image_store.destroy

    respond_to do |format|
      format.html { redirect_to admins_url }
    end
  end

  private

  def content_type_of_filename(filename)
    case File.extname(filename)
    when 'jpg', 'jpeg'
      'image/jpeg'
    when 'png'
      'image/png'
    else
      'application/octet-stream'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
	def authentication_required
  	if !session[:logged]
  		redirect_to login_url
  	end
  end
  
end

app/controllers/contact_controller.rb
#encoding: utf-8

class ContactController < ApplicationController
layout 'contact'

	def new
	  @message = Message.new
	end

	def create
	  @message = Message.new(params[:message])
	  
	  if @message.valid?
	   	ContactMailer.contact_message(@message).deliver
	    redirect_to root_url
	  else
	    render :action => 'new'
	  end
	end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  
  def index
    @image_stores = ImageStore.all

    respond_to do |format|
      format.html # index.html.erb
    end 
  end

  def show
    @image_store = ImageStore.find(params[:id])
    @images = Image.all


    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'login'

  def new
  end

  #recup des data du form pour le login et test validation
  def create
  	if params[:name] == 'maoui' && params[:password] == 'f0T0$313'
  		session[:logged] = true
  		redirect_to admins_url
  	else
  		session[:logged] = false
  		redirect_to login_url, :alert => "Invalid user/password combination"
  	end
  end

  #detruire la session
  def destroy
  	session[:logged] = false
  	redirect_to galleries_url, :notice => "Logged out"
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/admin/_form.html.erb
  <hr /><br/>
  <%= form_for @image_store, :url => (@image_store.new_record? ? admins_path : admin_path(@image_store.id)), :html => {:multipart => true} do |f| %>
    <div>
    	<%= f.label 'Nom de la gallerie' %><%= f.text_field :name, :required => 'required' %>
    </div>
    <div>
    	<%= f.label :Description %><%= f.text_field :description, :required => 'required'  %>
    </div>
    <div>
      <%= f.label 'Fichier ZIP'  %><%= f.file_field :image %>  
    </div><hr />
    <div class="actions">
      <%= f.submit "Ajouter", :class => 'btn btn-success' %>
      <%= link_to 'Retour', {:controller => "admin", :action => "index"}, :class => 'btn btn-inverse' %>
    </div>
  <% end %>
  <div>
</div>

app/views/admin/edit.html.erb
<div class="span9 content_admin">
  <div class="content">
  <h1>Edit galerie</h1>
<%= render 'form' %>

app/views/admin/index.html.erb
<div class="span9 gallery_admin">
  <% @image_stores.each do |store| %>
    <%= div_for(store, :class => "gallery") do %>
      <table border="0">
        <tr>
          <td id="store_name"><h1><%= store.name  %></h1></td>
          <td><p id="datetime"><%= time_tag store.created_at, :format => '%d.%m.%y' %></p></td>
        </tr>
        <tr>
          <td id="desc"><%= store.description %></td>
        </tr>
        <tr>
          <td colspan="2">
          <ul class="thumbnails row">    
            <% images = store.images %> 
            <% 1.upto(3) do |index| %>      
              <li class="thumbnail span3">
                <%= image_tag images[index-1].image if !images[index-1].nil? %>  
              </li>     
            <% end %>      
          </ul>
          </td>
        </tr>
      </table>
      <table border="0">
        <tr>
          <td>
            <%= link_to 'Editer', {:controller => 'admin', :action => 'edit', :id => store.id}, :class => 'btn btn-info' %>
            <%= link_to 'Supprimer', admin_path(store), :method => 'delete', :confirm => 'Are you sure ?', :class => 'btn btn-danger' %>
          </td>
        </tr>
      </table>
    <% end %>
  <% end %>
</div>

app/views/admin/new.html.erb
<div class="span9 content_admin">
  <div class="content">
  <h1>Nouvelle galerie</h1>
<%= render 'form' %>

app/views/contact/new.html.erb
<div class="span12 gallery gallery_div">
  <div class="form">
  <h1>Contactez-moi</h1><hr />
  <%= form_for @message, :url => contact_path do |f| %>
    <% if @message.errors.any? %>
      <h4>Erreur dans le formulaire :</h4>
      <% @message.errors.each do |attr,msg|  %>
        <li class="error"><%= msg %></li>
      <% end %> 
    <% end %><br />
    <div></div>
    <div class="field_label">
      <%= f.label "Prénom", :class => "label_name" %><%= f.label 'Email', :class => "label_email" %>
    </div>
    <div class="field">
      <%= f.text_field :name, :class => "field_name" %><%= f.email_field :email, :class => "field_email" %>
    </div><br />
    <div class="field_message">
      <%= f.label 'Message' %>
      <%= f.text_area :content, :rows => 6, :class => "message" %>
    </div><br />
    <div class="field_submit">
      <%= f.submit 'Envoyer message', :class => "btn btn-inverse" %>
    </div>
  <% end %>
  </div>
</div>

app/views/galleries/index.html.erb
<div class="span9 gallery_div">
  <% @image_stores.each do |store| %>
    <%= div_for(store, :class => "gallery") do %>
      <table border="0">
        <tr>
          <td id="store_name"><h1><%= link_to store.name, :controller => "galleries", :action => "show", :id => store.id, :class => 'title_link' %></h1></td>
          <td><p id="datetime"><%= time_tag store.created_at, :format => '%d.%m.%y' %></p></td>
        </tr>
        <tr>
          <td id="desc"><%= store.description %></td>
        </tr>
        <tr>
          <td colspan="2">
          <ul class="thumbnails row">    
            <% images = store.images %> 
            <% 1.upto(6) do |index| %>      
              <li class="thumbnail span3">
                <a href="<%= images[index-1].image if !images[index-1].nil? %>" rel='gallery'>
                <%= image_tag images[index-1].image if !images[index-1].nil? %>
                </a>  
              </li>     
            <% end %>      
          </ul>
          </td>
        </tr>
      </table>
      <table border="0">
        <tr>
          <td id="empty_col"></td>
          <td><div class="more"><%= link_to 'plus...', :controller => "galleries", :action => "show", :id => store.id %></div></td>
        </tr>
      </table>
    <% end %>
  <% end %>
</div>

app/views/galleries/show.html.erb
<div class="span9 gallery_div show">
  <% store = @image_store %>
    <%= div_for(store, :class => "gallery") do %>
      <table border="0">
        <tr>
          <td id="store_name"><h1><%= store.name  %></h1></td>
          <td><p id="datetime"><%= time_tag store.created_at, :format => '%d.%m.%y' %></p></td>
        </tr>
        <tr>
          <td id="desc"><%= store.description %></td>
        </tr>
        <tr>
          <td colspan="2">
          <ul class="thumbnails row">    
            <% images = store.images %> 
              <% images.each do |index| %>  
              <li class="thumbnail span3">
                <a href="<%= index.image if !index.nil?%>" rel='gallery'>   
                <%= image_tag index.image if !index.nil? %>  
                </a>
              </li>     
            <% end %>      
          </ul>
          </td>
        </tr>
      </table>
      <table border="0">
        <tr>
          <td id="empty_col"></td>
          <td><div class="retour"><%= link_to 'retour', {:controller => 'galleries', :action => 'index'} %></div></td>
        </tr>
      </table>  
    <% end %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Manon galeries</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="top_line"></div>
	<div class="navbar">
	  <div class="navbar-inner">
	    <div class="container">
	      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>
					<%= link_to "Manon galeries", galleries_path, :class => 'brand' %>
	      <div class="nav-collapse">
	        <ul class="nav">
					  <li class="dropdown">
					    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Galeries<b class="caret"></b></a>
					    <ul class="dropdown-menu">
								<% ImageStore.all.each do |image_store| %>
					      	<li>
  									<%= link_to image_store.name, gallery_path(image_store) %>
					      	</li>
								<% end %>
					    </ul>
					  </li>
					</ul>
	      </div>
	    </div>
	  </div>
	</div>
	<div class="container">
		<div class="row">
			<div class="span3">
				<div class="content_menu_admin">
					<h1>Admin Area</h1>
					<div class="list_menu"> 
						<ul class="nav nav-list">
							<div class="line_menu"></div>
							<li class="nav-header">menu administration</li>
							<li>
					    	<a href="/admin/new">
							    <i class="icon-upload"></i>
							    Nouvelle gallerie
							  </a>
							</li>
						  <hr />
						  	<%= link_to "Déconnexion", logout_path %>
						  </li>
						  <div class="line_menu"></div>
						</ul>
					</div>
				</div>
			</div>
			<%= yield %>
		</div>
	</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Manon galeries</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="top_line"></div>
	<div class="navbar">
	  <div class="navbar-inner">
	    <div class="container">
	      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>
					<%= link_to "Manon galeries", galleries_path, :class => 'brand' %>
	      <div class="nav-collapse">
	        <ul class="nav">
					  <li class="dropdown">
					    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Galeries<b class="caret"></b></a>
					    <ul class="dropdown-menu">
								<% ImageStore.all.each do |image_store| %>
					      	<li>
  									<%= link_to image_store.name, gallery_path(image_store) %>
					      	</li>
								<% end %>
					    </ul>
					  </li>
					</ul>
	      </div>
	    </div>
	  </div>
	</div>
	<div class="container">
		<div class="row">
			<%= yield %>
			<div class="span3">
				<div class="about_me"><h2><span class="hashtag">#</span> Moi</h2>
					Amatrice passionnée depuis quelques années, j’aime promener mes yeux à la recherche d’une expression sur un visage, d’un recoin dans une ville… tentant de faire renaître, aussi éphémère soit-il, le brin d’émotion qui m’aura habité durant quelques instants.
				</div>
			</div>
		</div>
	</div>
	<div class="footer">
		<div id="content_footer">© 2012 - Ludovic Turmel - All rights reserved</div>
	</div>
</body>
</html>

app/views/layouts/contact.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Manon galeries</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="top_line"></div>
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
          <%= link_to "Manon galeries", galleries_path, :class => 'brand' %>
        <div class="nav-collapse">
          <ul class="nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Galeries<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% ImageStore.all.each do |image_store| %>
                  <li>
                    <%= link_to image_store.name, gallery_path(image_store) %>
                  </li>
                <% end %>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <%= yield %>
    </div>
  </div>
  <div class="footer">
    <div id="content_footer">© 2012 - Ludovic Turmel - All rights reserved</div>
  </div>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Manon galeries</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="top_line"></div>
	<div class="navbar">
	  <div class="navbar-inner">
	    <div class="container">
	      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>
					<%= link_to "Manon galeries", galleries_path, :class => 'brand' %>
	      <div class="nav-collapse">
	        <ul class="nav">
					  <li class="dropdown">
					    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Galeries<b class="caret"></b></a>
					    <ul class="dropdown-menu">
								<% ImageStore.all.each do |image_store| %>
					      	<li>
  									<%= link_to image_store.name, gallery_path(image_store) %>
					      	</li>
								<% end %>
					    </ul>
					  </li>
					</ul>
	      </div>
	    </div>
	  </div>
	</div>
	<div class="container">
		<div class="row">
			<%= yield %>
		</div>
	</div>
</body>
</html>